#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    verkefni1-web-80-http:
      entrypoints:
        - http-8080
      rule: HostRegexp(`^verkefni1\.ddev\.site$`)
      
      service: "verkefni1-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "verkefni1-redirectHttps"
    verkefni1-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^verkefni1\.ddev\.site$`)
      
      service: "verkefni1-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "verkefni1-redirectHttps"
    
    
    
    verkefni1-web-80-https:
      entrypoints:
        - http-8443
      rule: HostRegexp(`^verkefni1\.ddev\.site$`)
      
      service: "verkefni1-web-80"
      ruleSyntax: v3
      
      tls: true
      
    verkefni1-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^verkefni1\.ddev\.site$`)
      
      service: "verkefni1-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    verkefni1-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    verkefni1-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-verkefni1-web:80
        
    verkefni1-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-verkefni1-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/verkefni1.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/verkefni1.key